name: Git Subtree Push

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  subtree:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Subtree
        run: git subtree push --prefix dist origin gh-pages
