# Simple workflow for deploying static content to GitHub Pages
name: Git Subtree Push

on:
  push:
    branches: ["main"]
    paths:
      - "${{inputs.build_folder}}"

jobs:
  subtree:
    uses: jaingam/git-subtree-to-branch@v0.0.3
          
          
