# Simple workflow for deploying static content to GitHub Pages
name: Git Subtree Push

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  subtree:
    uses: jaingam/git-subtree-to-branch@v0.0.1
